### ISSUE TITLE
Failure to call onNativeAdLoaded and/or onNativeAdFailed disrupt the mediation waterfall and cause future ad requests to stall.

### ISSUE THREAD

**Issue by Luklek** [flurry/FlurryAdapterForMoPubAndroid#15]
I noticed that the first time a flurry native ad is loaded, it doesn't call/log onNativeAdLoaded or onNativeAdFailed and so disrupt the mediation waterfall (and the placement is stalled and not show any other ads).
This happen only the first time the app is launched and only for the first flurry ad request.
If I manually set to refresh ads after 30 seconds (see logcat below), on this following request everything works fine and flurry ads are fetched and displayed properly.
Also, if I load flurry native ads in more than 1 placement, only the placement loaded first will be stuck. The flurry ads loaded subsequently in the other placements will work properly.

09-07 00:36:22.969 10251-10251/com.my.application.prova D/MoPub: Attempting to invoke custom event: com.mopub.nativeads.FlurryCustomEventNative
09-07 00:36:22.969 10251-10251/com.my.application.prova I/FlurryCustomEventNative: ServerInfo fetched from Mopub apiKey : and adSpaceName :Native
09-07 00:36:23.105 10251-10251/com.my.application.prova D/FlurryCustomEventNative: Fetching Flurry Native Ad now.
**09-07 00:36:52.151 10251-10251/com.my.application.prova D/MoPub: Refreshing NativeStatic ads**
09-07 00:36:52.633 10251-10251/com.my.application.prova D/MoPub: Attempting to invoke custom event: com.mopub.nativeads.FlurryCustomEventNative
09-07 00:36:52.633 10251-10251/com.my.application.prova I/FlurryCustomEventNative: ServerInfo fetched from Mopub apiKey : and adSpaceName :Native
09-07 00:36:52.634 10251-10251/com.my.application.prova D/FlurryCustomEventNative: Fetching Flurry Native Ad now.
09-07 00:36:52.751 10251-10251/com.my.application.prova D/FlurryCustomEventNative: onFetched: Native Ad fetched successfully!
09-07 00:36:52.756 10251-10251/com.my.application.prova D/FlurryCustomEventNative: Flurry Native Ad main image found.
09-07 00:36:52.756 10251-10251/com.my.application.prova D/FlurryCustomEventNative: Flurry Native Ad icon image found.
09-07 00:36:52.756 10251-10251/com.my.application.prova D/FlurryCustomEventNative: Flurry Native Ad main image found.
09-07 00:36:52.756 10251-10251/com.my.application.prova D/FlurryCustomEventNative: Flurry Native Ad icon image found.
09-07 00:36:53.669 10251-10251/com.my.application.prova D/FlurryCustomEventNative: preCacheImages: Ad image cached.
09-07 00:36:53.670 10251-10251/com.my.application.prova D/FlurryCustomEventNative: prepare(com.flurry.android.ads.FlurryAdNative@20893c9 android.widget.FrameLayout{1846db93 V.ED..C. ......I. 0,0-0,0 #7f0d00b5 app:id/native_ad_view})
09-07 00:36:54.718 10251-10251/com.my.application.prova D/FlurryCustomEventNative: onImpressionLogged

**Comment by ugonna** [comment]
Hi, @Luklek. Thanks for reporting this in. To make it easier to follow up on, please send such reports to integration [AT] flurry {dot} com. You should also avoid sharing your app credentials here.
