### ISSUE TITLE
No rendered registered

### ISSUE THREAD

**Issue by mindwalkr** [flurry/FlurryAdapterForMoPubAndroid#17]
Implemented this tonight, and ads don't show.  In addition, I see:
D/FlurryCustomEventNative: Fetching Flurry Native Ad now.
D/FlurryCustomEventNative: onFetched: Flurry native ad fetched successfully!
D/FlurryCustomEventNative: Flurry Native Ad main image found.
D/FlurryCustomEventNative: Flurry Native Ad icon image found.
D/FlurryCustomEventNative: Flurry Native Ad main image found.
D/FlurryCustomEventNative: Flurry Native Ad icon image found.
D/FlurryCustomEventNative: preCacheImages: Ad image cached.

V/MoPub: Native Ad failed to load with error: A required renderer was not registered for the CustomEventNative..

.... bug ?

**Comment by ugonna** [comment]
Hi @mindwalkr. You'll need to register the `FlurryNativeAdRenderer` class with the MoPub SDK.

```java
ViewBinder binder = new ViewBinder.Builder(R.layout.native_ad_list_item)
          // Set up your regular ViewBinder
          .build();

// Configure FlurryViewBinder with your video view
FlurryViewBinder flurryBinder = new FlurryViewBinder.Builder(binder)
          .videoViewId(R.id.native_video_view)
          .build();

// Register the FlurryNativeAdRenderer to handle both Flurry video and static native ads
final FlurryNativeAdRenderer flurryRenderer = new FlurryNativeAdRenderer(flurryBinder);
mAdAdapter = new MoPubAdAdapter(getActivity(), adapter);
mAdAdapter.registerAdRenderer(flurryRenderer);

//...register other native ad renderers as required
```

Alternatively, you can remove the class from your classpath entirely to get the adapter to proceed without it. As long as the class is in your project, the adapter will need it to be registered as above. 

You can check out the [README](https://github.com/flurry/flurry-adapter-mopub-android/blob/master/README.md) to learn more.

**Comment by mindwalkr** [comment]
Thanks!
