### ISSUE TITLE
Clicks not working with RecyclerView 

### ISSUE THREAD

**Issue by InterestingTime** [flurry/FlurryAdapterForMoPubAndroid#18]
I am using a RecyclerView and MoPub's RecyclerView adapter.

When a click event happens on a flurry ad, it starts working like it should, pausing the activity, but then nothing happens and the activity resumes.

I have 5 other networks in my stack and this problem only happens with Flurry ads.

**Comment by InterestingTime** [comment]
Some logs:

`01-12 13:58:26.567 23712-23712/org.# D/MoPub: Attempting to invoke custom event: com.mopub.nativeads.FlurryCustomEventNative
01-12 13:58:26.567 23712-23712/org.# I/FlurryCustomEventNative: ServerInfo fetched from Mopub apiKey : # and adSpaceName :Native Banner
01-12 13:58:26.568 23712-23712/org# D/FlurryCustomEventNative: Fetching Flurry Native Ad now.
01-12 13:58:26.611 23712-23712/org.# D/FlurryCustomEventNative: onFetched: Native Ad fetched successfully!
01-12 13:58:26.631 23712-23712/org.# D/FlurryCustomEventNative: Flurry Native Ad main image found.
01-12 13:58:26.631 23712-23712/org.# D/FlurryCustomEventNative: Flurry Native Ad icon image found.
01-12 13:58:26.631 23712-23712/org.# D/FlurryCustomEventNative: Flurry Native Ad main image found.
01-12 13:58:26.631 23712-23712/org.# D/FlurryCustomEventNative: Flurry Native Ad icon image found.
01-12 13:58:26.805 23712-23712/org.# D/FlurryCustomEventNative: preCacheImages: Ad image cached.
01-12 13:58:27.067 23712-23712/org.# D/FlurryCustomEventNative: onImpressionLogged
01-12 13:58:34.859 23712-23712/org.# D/FlurryCustomEventNative: onClicked
01-12 13:58:34.863 5321-6537/system_process I/ActivityManager: START u0 {cmp=org.#/com.flurry.android.FlurryFullscreenTakeoverActivity (has extras)} from uid 10379 on display 0
01-12 13:58:34.867 23712-23712/org.# D/FlurryCustomEventNative: destroy(com.flurry.android.ads.FlurryAdNative@8ef2255) started.
01-12 13:58:34.873 23712-23712/org.# D/FlurryCustomEventNative: destroy(com.flurry.android.ads.FlurryAdNative@c16432b) started.`

`01-12 13:58:35.038 23712-23712/org.# E/FlurryAgent: Cannot launch Activity. No ad object.
01-12 13:58:35.042 23712-23712/org.# E/FlurryAgent: FlurryFullscreenTakeoverActivity cannot be launched as the internal ad object could not be found. Please ensure that the ad object is displayed in the same Context in which it was created, and that the ad object was not deleted.
01-12 13:58:35.196 23712-23712/org.# E/FlurryAgent: FlurryFullscreenTakeoverActivity cannot destroy internal ad object as the object could not be found. Please ensure that the ad object is displayed in the same Context in which it was created, and that the ad object was not deleted.`

**Comment by InterestingTime** [comment]
Also this only happens when using RecyclerView, ListView is ok. The RecyclerView is in a fragment and the context used to create the adapters is getActivity()

**Comment by InterestingTime** [comment]
This is my fault, I was calling clearAds method onPause.

**Comment by ugonna** [comment]
Thanks for the update, @simpleforreddit. Glad to know you've figured out the issue.
