### ISSUE TITLE
java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection

### ISSUE THREAD

**Issue by joeykrim** [flurry/FlurryAdapterForMoPubAndroid#3]
Native Ads don't load when using Flurry 6.0.0 and MoPub 3.11.0 (and 3.10.0).

Logcat:
09-20 12:42:39.747 23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Fetching Flurry Native Ad now.
09-20 12:42:42.911 23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ onFetched(com.flurry.android.ads.FlurryAdNative@434ba13) Successful.
09-20 12:42:42.911 23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ FlurryForwardingNativeAd onFetched: Native Ad fetched successfully! com.flurry.android.ads.FlurryAdNative@434ba13
09-20 12:42:42.921 23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad main image found.
09-20 12:42:42.921 23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad icon image found.
09-20 12:42:42.921 23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad main image found.
09-20 12:42:42.921 23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad icon image found.
09-20 12:42:42.921 23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad main image found.
09-20 12:42:42.921 23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad icon image found.
09-20 12:42:42.931 23403-23552/joeykrim E/Volley﹕ [7633] NetworkDispatcher.run: Unhandled exception java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
at com.mopub.volley.toolbox.HurlStack.createConnection(HurlStack.java:152)
at com.mopub.volley.toolbox.HurlStack.openConnection(HurlStack.java:162)
at com.mopub.volley.toolbox.HurlStack.performRequest(HurlStack.java:102)
at com.mopub.network.RequestQueueHttpStack.performRequest(RequestQueueHttpStack.java:52)
at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
09-20 12:42:42.931 23403-23550/joeykrim E/Volley﹕ [7631] NetworkDispatcher.run: Unhandled exception java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
at com.mopub.volley.toolbox.HurlStack.createConnection(HurlStack.java:152)
at com.mopub.volley.toolbox.HurlStack.openConnection(HurlStack.java:162)
at com.mopub.volley.toolbox.HurlStack.performRequest(HurlStack.java:102)
at com.mopub.network.RequestQueueHttpStack.performRequest(RequestQueueHttpStack.java:52)
at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
09-20 12:42:43.031 23403-23403/joeykrim D/MoPub﹕ Failed to download a native ads image:
com.mopub.volley.VolleyError: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:141)
Caused by: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
at com.mopub.volley.toolbox.HurlStack.createConnection(HurlStack.java:152)
at com.mopub.volley.toolbox.HurlStack.openConnection(HurlStack.java:162)
at com.mopub.volley.toolbox.HurlStack.performRequest(HurlStack.java:102)
at com.mopub.network.RequestQueueHttpStack.performRequest(RequestQueueHttpStack.java:52)
at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
09-20 12:42:43.031 23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ preCacheImages: Unable to cache Ad image. Error[Unable to download images associated with ad.]
09-20 12:42:43.031 23403-23403/joeykrim D/MoPub﹕ Failed to download a native ads image:
com.mopub.volley.VolleyError: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:141)
Caused by: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
at com.mopub.volley.toolbox.HurlStack.createConnection(HurlStack.java:152)
at com.mopub.volley.toolbox.HurlStack.openConnection(HurlStack.java:162)
at com.mopub.volley.toolbox.HurlStack.performRequest(HurlStack.java:102)
at com.mopub.network.RequestQueueHttpStack.performRequest(RequestQueueHttpStack.java:52)
at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

**Comment by joeykrim** [comment]
The error seems to be caused by the FlurryAdNative.getAsset call (https://github.com/flurry/FlurryAdapterForMoPubAndroid/blob/master/src/com/mopub/nativeads/FlurryForwardingNativeAd.java#L64) returning a local file location (Example: file:///storage/emulated/0/Android/data/com.joeykrim/files/.fcaches/fileStreamCacheDownloaderTmp/8/be48e13cdad21988), but MoPub's BaseForwardingNativeAd.setMainImageURL and setIconImageURL (https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/src/main/java/com/mopub/nativeads/BaseForwardingNativeAd.java#L67) are expecting a URL, not a local file location.

A terrible workaround that allows the Flurry Native Ad to display, but without the icon image, is to comment out the code passing the local file location into the MoPub Main and Icon URL methods and directly call: mCustomEventNativeListener.onNativeAdLoaded(mFlurryForwardingNativeAd);

**Comment by joeykrim** [comment]
The error seems to be caused by the FlurryAdNative.getAsset call (https://github.com/flurry/FlurryAdapterForMoPubAndroid/blob/master/src/com/mopub/nativeads/FlurryForwardingNativeAd.java#L64) returning a local file location (Example: file:///storage/emulated/0/Android/data/com.joeykrim/files/.fcaches/fileStreamCacheDownloaderTmp/8/be48e13cdad21988), but MoPub's BaseForwardingNativeAd.setMainImageURL and setIconImageURL (https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/src/main/java/com/mopub/nativeads/BaseForwardingNativeAd.java#L67) methods are expecting a URL, not a local file location.

An easy method to surface the issue of passing Flurry's local file locations to MoPub's URL methods is to change two lines:
1) https://github.com/flurry/FlurryAdapterForMoPubAndroid/blob/master/src/com/mopub/nativeads/FlurryForwardingNativeAd.java#L122 to Log.d(kLogTag, "Flurry Native Ad main image found: " + getMainImageUrl()); 
2) https://github.com/flurry/FlurryAdapterForMoPubAndroid/blob/master/src/com/mopub/nativeads/FlurryForwardingNativeAd.java#L128 to Log.d(kLogTag, "Flurry Native Ad icon image found: " + getIconImageUrl());

A terrible workaround that allows the Flurry Native Ad to display, but without the icon image, is to comment out the Flurry code passing the local file location into the MoPub Main and Icon URL methods and instead directly call: mCustomEventNativeListener.onNativeAdLoaded(mFlurryForwardingNativeAd);

It seems that the MoPub Native Ad adapter insists on loading the image URLs before displaying them and doesn't seem to be able to load the images from local files, which is all that the Flurry Native Ads SDK seems to provide?
I'm not able to sort out how to get the Flurry Native Ad image URLs as they don't seem to be exposed? I'm going by the [public methods](http://flurrydev.github.io/FlurryAndroidSDK5xAPI/classcom_1_1flurry_1_1android_1_1ads_1_1FlurryAdNative.html) and reversed SDK code...

**Comment by ugonna** [comment]
The Flurry SDK passes image assets to MoPub as HTTP URLs, as long as Flurry can identify that the ad request is sent from this adapter.

Check the `FlurryAgentWrapper` class in your copy of the adapter and ensure that [this `FlurryAgent.addOrigin(String, String)` line](https://github.com/flurry/FlurryAdapterForMoPubAndroid/blob/master/src/com/mopub/mobileads/FlurryAgentWrapper.java#L34) is still present and unchanged.

**Comment by joeykrim** [comment]
The directions for the FlurryAgentWrapper class indicate that the FlurryAgentWrapper class it isn't required for analytics users. I thought that by initializing Flurry analytics (FlurryAgent.init(this, "account_number");) in onCreate before calls to the Native Ads, I would be considered a Flurry Analytics user and not need the FlurryAgentWrapper class.
According to the guidance from @Ugonna, the FlurryAgentWrapper class is indeed required, regardless of whether Flurry Analytics are initialized?
Directions are cited in three places:
1) 3) ["This class is not required for Flurry Analytics users. It may safely be deleted for apps that already integrate Analytics."](https://github.com/flurry/FlurryAdapterForMoPubAndroid/blob/master/src/com/mopub/mobileads/FlurryAgentWrapper.java#L16) - FlurryAgentWrapper.java
2) ["Not needed for Flurry Analytics users"](https://github.com/flurry/FlurryAdapterForMoPubAndroid/blob/master/src/com/mopub/nativeads/FlurryCustomEventNative.java#L51) - FlurryAgentWrapper.getInstance().onStartSession(context, flurryApiKey); in FlurryCustomEventNative.java 
3) ["Not needed for Flurry Analytics users"](https://github.com/flurry/FlurryAdapterForMoPubAndroid/blob/master/src/com/mopub/nativeads/FlurryForwardingNativeAd.java#L154) - FlurryAgentWrapper.getInstance().onEndSession(mContext); in FlurryForwardingNativeAd.java

Adding the [FlurryAgentWrapper](https://github.com/flurry/FlurryAdapterForMoPubAndroid/blob/master/src/com/mopub/mobileads/FlurryAgentWrapper.java) class to com.mopub.mobileads fixed the issue. Without the FlurryAgentWrapper class, local file locations were being passed rather than URLs. With the FlurryAgentWrapper class, URL locations are now being passed properly.
Thanks!

**Comment by bobroalexandr** [comment]
@joeykrim  I have same issue for facebook audience network integration.

**Comment by ugonna** [comment]
Hi, @bobroalexandr. I'm not sure I understand. Facebook Audience Network does not work with this adapter. What integration do you have exactly?

**Comment by bobroalexandr** [comment]
@ugonna I'm using Flurry with Facebook Audience Network. That network is connected to Mopub using that adapters https://github.com/mopub/mopub-android-sdk/tree/master/extras/src/com/mopub/nativeads for Facebook. When I receiving Flurry Native ads via FAN I have problems [here](https://github.com/mopub/mopub-android-sdk/blob/master/extras/src/com/mopub/nativeads/FacebookNative.java#L163) and with other images (got links like file:///storage/sdcard/Android/data/project/files/.fcaches/fileStreamCacheDownloaderTmp/3/793e63476204234a). I have no idea what to do with that....

**Comment by bobroalexandr** [comment]
And I cannot understand why that issue happened and how was it fixed in your case

**Comment by ugonna** [comment]
The Facebook adapters do not receive Flurry ads. If using Flurry, you need to configure your MoPub ad unit so that `FlurryCustomEventNative` receives the call, not Facebook.

**Comment by bobroalexandr** [comment]
![image](https://cloud.githubusercontent.com/assets/3910140/20015567/a01f2fbc-a2c4-11e6-9858-942d47c783f2.png)
that's from FAN mediation

**Comment by bobroalexandr** [comment]
anyway @ugonna can you please explain how this issue (that in this ticket) was faced and how did you solve it?
