### ISSUE TITLE
FlurryAdapterForMoPubAndroid build fail

### ISSUE THREAD

**Issue by jtfang** [flurry/FlurryAdapterForMoPubAndroid#5]
Dear Author : 
First of all, thanks for your module to give us a shortcut to integrate with mopub.
But there is a build break in source code with the following error message : 
[Error Message]
FlurryCustomEventNative.java:40: error: cannot find symbol
        final FlurryStaticNative mflurryStaticNative =
              ^
  symbol:   class FlurryStaticNative
  location: class FlurryCustomEventNative

It seems there is a typo in the class - com.mopub.nativeads.FlurryCustomEventNative
FlurryStaticNative should use FlurryStaticNativeAd instead.
I guess the correct one may be
        final FlurryStaticNativeAd mflurryStaticNative =
                new FlurryStaticNativeAd(context,
                        new FlurryAdNative(context, flurryAdSpace), customEventNativeListener);

Please let me know if I'm misunderstanding.

**Comment by ugonna** [comment]
Thanks for pointing out the typo, @jtfang. This has been corrected.
